# Generated by Django 3.2 on 2022-07-03 06:23

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(db_column='password', max_length=88, verbose_name='密码')),
                ('email', models.CharField(db_column='email', max_length=225, unique=True, verbose_name='邮箱')),
                ('head_portrait', models.CharField(db_column='head_portrait', default='https://wwc.alicdn.com/avatar/getAvatar.do?userNick=tb758136261', max_length=225, verbose_name='头像')),
                ('delete_portrait', models.CharField(max_length=225, null=True, verbose_name='删除头像')),
                ('balance', models.IntegerField(db_column='balance', default=10000, verbose_name='余额')),
                ('payPassword', models.CharField(blank=True, max_length=25, null=True, verbose_name='支付密码')),
                ('is_active', models.IntegerField(choices=[(0, '未激活'), (1, '激活')], db_column='is_active', default=0, verbose_name='状态')),
                ('created_time', models.DateTimeField(db_column='creat_time', default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(db_column='last_time', default=django.utils.timezone.now, verbose_name='修改时间')),
                ('introduce', models.CharField(default='普通人', max_length=255, verbose_name='用户的个人简介')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
